// <auto-generated />
using System;
using Bcp.Exchange.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bcp.Exchange.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ExchangeDbContext))]
    [Migration("20251106063853_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bcp.Exchange.Core.BoundedContexts.Configuration.Entities.Parameter", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LongDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("NumericValue")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ParentId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TextValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.HasIndex("ParentId1");

                    b.ToTable("Parameters", (string)null);
                });

            modelBuilder.Entity("Bcp.Exchange.Core.BoundedContexts.ExchangeRates.Entities.ExchangeRate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("CurrencySourceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CurrencyTargetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyTargetId");

                    b.HasIndex("CurrencySourceId", "CurrencyTargetId", "IsActive")
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("ExchangeRates", (string)null);
                });

            modelBuilder.Entity("Bcp.Exchange.Core.BoundedContexts.Configuration.Entities.Parameter", b =>
                {
                    b.HasOne("Bcp.Exchange.Core.BoundedContexts.Configuration.Entities.Parameter", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bcp.Exchange.Core.BoundedContexts.Configuration.Entities.Parameter", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId1");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Bcp.Exchange.Core.BoundedContexts.ExchangeRates.Entities.ExchangeRate", b =>
                {
                    b.HasOne("Bcp.Exchange.Core.BoundedContexts.Configuration.Entities.Parameter", "CurrencySource")
                        .WithMany()
                        .HasForeignKey("CurrencySourceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bcp.Exchange.Core.BoundedContexts.Configuration.Entities.Parameter", "CurrencyTarget")
                        .WithMany()
                        .HasForeignKey("CurrencyTargetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CurrencySource");

                    b.Navigation("CurrencyTarget");
                });

            modelBuilder.Entity("Bcp.Exchange.Core.BoundedContexts.Configuration.Entities.Parameter", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
